# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_U4iIxeXe3W-4IkAXykm9VcqA5pPXvGQ
"""

def predict(model,input_data,tokenizer,input):
    import numpy as np
    input_ids,attention_mask = input_data
    start_pred , end_pred = model.predict((input_data))
    ip_data = input[['text','sentiment']]
    pred_text=[]
    for i in range(input_ids.shape[0]):
        a = np.argmax(start_pred[i])
        b=np.argmax(end_pred[i])
        text1 = " "+" ".join(ip_data['text'].values[i].split())
        enc = tokenizer.encode(text1)
        st = tokenizer.decode(enc[a:b+1])
        pred_text.append(st)


    return pred_text