# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_U4iIxeXe3W-4IkAXykm9VcqA5pPXvGQ
"""

def get_tokenizer(tokenizer_path):

    print('Loading Pretrained Tokenizer for TfRoberta model')
    print('*'*50)
    from transformers import RobertaTokenizer
    tokenizer = RobertaTokenizer.from_pretrained(tokenizer_path,add_prefix_space=True)

    return tokenizer